export const CategoriesItems = [
    "All",
    "Javascript",
    "Robotics",
    "Cybersecurity",
    "Data Science",
    "Top Movies",
    "CGI",
    "Esport",
    "Computer Science",
    "Technology",
    "Hardware",
    "rpg games",
    "japenese anime",
    "frontend",
    "NASA",
    "Devops",
];
