export const VideosItems = [
    {
        image: "/images/freecodecamp.jpeg.jpg",
        logoImg: "/images/unnamed (1).jpg",
        title: "junior developers common mistakes",
        channelName: "frrecodecamp",
        views: "2.3m",
        publishTime: "14 days ago",
    },
    {
        image: "/images/a72dcec6d4fb54bb50c1f4880757c6df1c6258036e014fe03480fd0f127ad68d.jpg",
        logoImg: "/images/unnamed (3).jpg",
        title: "top ten anime of all time",
        channelName: "frrecodecamp",
        views: "2.3m",
        publishTime: "14 days ago",
    },
    {
        image: "/images/freecodecamp.jpeg.jpg",
        logoImg: "/images/unnamed.jpg",
        title: "JS full Course 2023",
        channelName: "freecodecamp",
        views: "2.3m",
        publishTime: "14 days ago",
    },
    {
        image: "images/featured.webp",
        logoImg: "/images/unnamed (4).jpg",
        title: "Docker in 100 seconds",
        channelName: "fireship",
        views: "3m",
        publishTime: "14 days ago",
    },
    {
        image: "/images/maxresdefault.jpg",
        logoImg: "/images/unnamed (5).jpg",
        title: "Starcraft game movie",
        channelName: "game trailer",
        views: "163k",
        publishTime: "2 month ago",
    },
    {
        image: "/images/freecodecamp.jpeg.jpg",
        logoImg: "/images/unnamed (1).jpg",
        title: "junior developers common mistakes",
        channelName: "frrecodecamp",
        views: "2.3m",
        publishTime: "14 days ago",
    },
    {
        image: "/images/a72dcec6d4fb54bb50c1f4880757c6df1c6258036e014fe03480fd0f127ad68d.jpg",
        logoImg: "/images/unnamed (3).jpg",
        title: "top ten anime of all time",
        channelName: "frrecodecamp",
        views: "2.3m",
        publishTime: "14 days ago",
    },
    {
        image: "/images/freecodecamp.jpeg.jpg",
        logoImg: "/images/unnamed.jpg",
        title: "JS full Course 2023",
        channelName: "freecodecamp",
        views: "2.3m",
        publishTime: "14 days ago",
    },
    {
        image: "images/featured.webp",
        logoImg: "/images/unnamed (4).jpg",
        title: "Docker in 100 seconds",
        channelName: "fireship",
        views: "3m",
        publishTime: "14 days ago",
    },
    {
        image: "/images/maxresdefault.jpg",
        logoImg: "/images/unnamed (5).jpg",
        title: "Starcraft game movie",
        channelName: "game trailer",
        views: "163k",
        publishTime: "2 month ago",
    },
    {
        image: "/images/freecodecamp.jpeg.jpg",
        logoImg: "/images/unnamed (1).jpg",
        title: "junior developers common mistakes",
        channelName: "frrecodecamp",
        views: "2.3m",
        publishTime: "14 days ago",
    },
    {
        image: "/images/a72dcec6d4fb54bb50c1f4880757c6df1c6258036e014fe03480fd0f127ad68d.jpg",
        logoImg: "/images/unnamed (3).jpg",
        title: "top ten anime of all time",
        channelName: "frrecodecamp",
        views: "2.3m",
        publishTime: "14 days ago",
    },
    {
        image: "/images/freecodecamp.jpeg.jpg",
        logoImg: "/images/unnamed.jpg",
        title: "JS full Course 2023",
        channelName: "freecodecamp",
        views: "2.3m",
        publishTime: "14 days ago",
    },
    {
        image: "images/featured.webp",
        logoImg: "/images/unnamed (4).jpg",
        title: "Docker in 100 seconds",
        channelName: "fireship",
        views: "3m",
        publishTime: "14 days ago",
    },
    {
        image: "/images/maxresdefault.jpg",
        logoImg: "/images/unnamed (5).jpg",
        title: "Starcraft game movie",
        channelName: "game trailer",
        views: "163k",
        publishTime: "2 month ago",
    },
    {
        image: "/images/freecodecamp.jpeg.jpg",
        logoImg: "/images/unnamed (1).jpg",
        title: "junior developers common mistakes",
        channelName: "frrecodecamp",
        views: "2.3m",
        publishTime: "14 days ago",
    },
    {
        image: "/images/a72dcec6d4fb54bb50c1f4880757c6df1c6258036e014fe03480fd0f127ad68d.jpg",
        logoImg: "/images/unnamed (3).jpg",
        title: "top ten anime of all time",
        channelName: "frrecodecamp",
        views: "2.3m",
        publishTime: "14 days ago",
    },
    {
        image: "/images/freecodecamp.jpeg.jpg",
        logoImg: "/images/unnamed.jpg",
        title: "JS full Course 2023",
        channelName: "freecodecamp",
        views: "2.3m",
        publishTime: "14 days ago",
    },
    {
        image: "images/featured.webp",
        logoImg: "/images/unnamed (4).jpg",
        title: "Docker in 100 seconds",
        channelName: "fireship",
        views: "3m",
        publishTime: "14 days ago",
    },
    {
        image: "/images/maxresdefault.jpg",
        logoImg: "/images/unnamed (5).jpg",
        title: "Starcraft game movie",
        channelName: "game trailer",
        views: "163k",
        publishTime: "2 month ago",
    },
    {
        image: "/images/freecodecamp.jpeg.jpg",
        logoImg: "/images/unnamed (1).jpg",
        title: "junior developers common mistakes",
        channelName: "frrecodecamp",
        views: "2.3m",
        publishTime: "14 days ago",
    },
    {
        image: "/images/a72dcec6d4fb54bb50c1f4880757c6df1c6258036e014fe03480fd0f127ad68d.jpg",
        logoImg: "/images/unnamed (3).jpg",
        title: "top ten anime of all time",
        channelName: "frrecodecamp",
        views: "2.3m",
        publishTime: "14 days ago",
    },
    {
        image: "/images/freecodecamp.jpeg.jpg",
        logoImg: "/images/unnamed.jpg",
        title: "JS full Course 2023",
        channelName: "freecodecamp",
        views: "2.3m",
        publishTime: "14 days ago",
    },
    {
        image: "images/featured.webp",
        logoImg: "/images/unnamed (4).jpg",
        title: "Docker in 100 seconds",
        channelName: "fireship",
        views: "3m",
        publishTime: "14 days ago",
    },
    {
        image: "/images/maxresdefault.jpg",
        logoImg: "/images/unnamed (5).jpg",
        title: "Starcraft game movie",
        channelName: "game trailer",
        views: "163k",
        publishTime: "2 month ago",
    },
];
